// frontend/src/lib/components/insight/filters/FilterSelectorCard.svelte
<script lang="ts">
import { type Schema, schemaStore } from '$lib/client/schema'
import { Button } from '$lib/components/ui/button'
import * as Card from '$lib/components/ui/card'
import * as Command from '$lib/components/ui/command'
import * as Popover from '$lib/components/ui/popover'
import * as Select from '$lib/components/ui/select'
import type { Field, FieldFilter } from '$lib/queries/field'
import type { Operator } from '$lib/queries/operators'
import type { Selected } from 'bits-ui'
import { Check, ChevronsUpDown } from 'lucide-svelte'
import { createEventDispatcher, onMount } from 'svelte'

const schema: Schema = $schemaStore
$: availableFields = [
    { name: 'event_type', type: 'string' },
    ...schema.uniqueProperties,
] satisfies Field[]

$: eventTypes = Object.keys(schema.events)

$: propertyValues = schema.propertyValues
export const allOperators: Operator[] = [
    '=',
    '>',
    '<',
    '>=',
    '<=',
    '<>',
    'LIKE',
    'IN',
]
export let initialFilter: FieldFilter | null = null

const dispatch = createEventDispatcher()

let currentField: Field | null = null
let currentOperator: Selected<Operator> | undefined
let currentValue: string | undefined = ''
let openField = false
let openValue = false

$: isInitial =
    (initialFilter &&
        currentField === initialFilter.field &&
        currentOperator?.value === initialFilter.operator &&
        currentValue === initialFilter.value) ||
    (!currentField && !currentOperator && !currentValue)

onMount(() => {
    if (initialFilter) {
        currentField = initialFilter.field
        currentOperator = {
            value: initialFilter.operator,
            label: initialFilter.operator,
        }
        currentValue = initialFilter.value?.toString()
    }
})

function addFilter() {
    if (currentField && currentOperator && currentValue) {
        const newFilter: FieldFilter = {
            field: currentField,
            operator: currentOperator?.value,
            value: currentValue,
        }
        dispatch('save', newFilter)
        resetFields()
    }
}

function resetFields() {
    currentField = null
    currentOperator = undefined
    currentValue = ''
}

function handleDiscard() {
    resetFields()
    dispatch('discard')
}
</script>

<Card.Root class="w-full max-w-md border-0 shadow-none overflow-hidden">
  <Card.Header>
    <Card.Title>{initialFilter ? 'Edit Filter' : 'Add Filter'}</Card.Title>
  </Card.Header>
  <Card.Content class="space-y-4">
    <div class="space-y-2">
      <label class="text-sm font-medium">Field</label>
      <Popover.Root bind:open={openField}>
        <Popover.Trigger asChild let:builder>
          <Button
            builders={[builder]}
            variant="outline"
            role="combobox"
            aria-expanded={openField}
            class="w-full justify-between"
          >
            <span>
              {currentField ? currentField.name : 'Select field...'}
              <span class="text-muted-foreground text-xs ml-2">{currentField?.type ?? ''}</span>
            </span>
            <ChevronsUpDown class="ml-2 h-4 w-4 shrink-0 opacity-50" />
          </Button>
        </Popover.Trigger>
        <Popover.Content class="w-[var(--radix-popover-trigger-width)] p-0">
          <Command.Root>
            <Command.Input placeholder="Search field..." />
            <Command.Empty>No field found.</Command.Empty>
            <Command.Group>
              {#each availableFields as field}
                <Command.Item
                  value={field.name}
                  onSelect={() => {
                    currentField = field;
                    openField = false;
                  }}
                >
                  <Check
                    class={currentField?.name === field.name
                      ? 'mr-2 h-4 w-4'
                      : 'mr-2 h-4 w-4 invisible'}
                  />
                  {field.name}
                  <span class="text-muted-foreground text-xs ml-2">{field.type}</span>
                </Command.Item>
              {/each}
            </Command.Group>
          </Command.Root>
        </Popover.Content>
      </Popover.Root>
    </div>

    <div class="space-y-2">
      <label class="text-sm font-medium">Filter</label>
      <Select.Root bind:selected={currentOperator}>
        <Select.Trigger class="w-full">
          <Select.Value placeholder="Select operator" />
        </Select.Trigger>
        <Select.Content>
          {#each allOperators as operator}
            <Select.Item value={operator}>{operator}</Select.Item>
          {/each}
        </Select.Content>
      </Select.Root>
    </div>

    <div class="space-y-2">
      <label class="text-sm font-medium">Value</label>
      <Popover.Root bind:open={openValue}>
        <Popover.Trigger asChild let:builder>
          <Button
            builders={[builder]}
            variant="outline"
            role="combobox"
            aria-expanded={openValue}
            class="w-full justify-between"
          >
            {currentValue || 'Enter value...'}
            <ChevronsUpDown class="ml-2 h-4 w-4 shrink-0 opacity-50" />
          </Button>
        </Popover.Trigger>
        <Popover.Content class="p-0" style="width: var(--radix-popover-trigger-width);">
          <Command.Root>
            <Command.Input placeholder="Enter value" bind:value={currentValue} />
            <Command.Empty>No suggestion found.</Command.Empty>
            <Command.Group class="overflow-y-auto max-h-[300px]">
              {#if currentField?.name === 'event_type'}
                {#each eventTypes as type}
                  <Command.Item
                    value={type}
                    onSelect={() => {
                      currentValue = type;
                      openValue = false;
                    }}
                  >
                    <Check
                      class={currentValue === type ? 'mr-2 h-4 w-4' : 'mr-2 h-4 w-4 invisible'}
                    />
                    {type}
                  </Command.Item>
                {/each}
              {/if}
              {#if currentField}
                {#each propertyValues[currentField.name] ?? [] as val}
                  <Command.Item
                    value={val}
                    onSelect={() => {
                      currentValue = val;
                      openValue = false;
                    }}
                  >
                    <Check
                      class={currentValue === val ? 'mr-2 h-4 w-4' : 'mr-2 h-4 w-4 invisible'}
                    />
                    {val}
                  </Command.Item>
                {/each}
              {/if}
            </Command.Group>
          </Command.Root>
        </Popover.Content>
      </Popover.Root>
    </div>
  </Card.Content>
  <Card.Footer class="flex justify-end space-x-2">
    <Button variant="outline" on:click={handleDiscard}>
      {#if isInitial}
        Cancel
      {:else}
        Discard Changes
      {/if}
    </Button>
    <Button on:click={addFilter}>{initialFilter ? 'Update' : 'Create'}</Button>
  </Card.Footer>
</Card.Root>

// frontend/src/components/filters/filter-selector-card.tsx
// src/components/filters/FilterSelectorCard.tsx
import {useEffect, useMemo, useState} from 'react'
import {Check, ChevronsUpDown} from 'lucide-react'
import {Card, CardContent, CardFooter, CardHeader, CardTitle,} from '@/components/ui/card'
import {Command, CommandEmpty, CommandInput, CommandItem, CommandList,} from '@/components/ui/command'
import {Popover, PopoverContent, PopoverTrigger,} from '@/components/ui/popover'
import {Select, SelectContent, SelectItem, SelectTrigger, SelectValue,} from '@/components/ui/select'
import {Button} from '@/components/ui/button'
import {Field, FieldFilter, Operator, operators} from "@/model/filters.ts";
import {usePropValues, useSchema} from "@/services/schemas.ts";
import {useProjectId} from "@/hooks/use-project-id.tsx";

interface Props {
    initialFilter?: FieldFilter
    onSave: (filter: FieldFilter) => void
    onDiscard: () => void
}

export function FilterSelectorCard
({
     initialFilter,
     onSave,
     onDiscard,
 }: Props) {
    const [currentField, setCurrentField] = useState<Field | null>(null)
    const [currentOperator, setCurrentOperator] = useState<Operator>('=')
    const [currentValue, setCurrentValue] = useState<string>('')
    const [openField, setOpenField] = useState(false)
    const [openValue, setOpenValue] = useState(false)

    const project = useProjectId()
    const schema = useSchema(project)

    useEffect(() => {
        if (initialFilter) {
            setCurrentField(initialFilter.field)
            setCurrentOperator(initialFilter.operator)
            setCurrentValue(initialFilter.value.toString())
        }
    }, [initialFilter])

    if (schema.isLoading || schema.isPending || schema.error) return null
    const availableFields = [
        {name: 'event_type', type: 'string'},
        ...schema.data.uniqueProperties,
    ] satisfies Field[]
    // const availableFields = ['a', 'b']

    const eventTypes = Object.keys(schema.data.events)

    const fieldId = useMemo(() =>
            schema.data.uniqueProperties
                .find(f => f.name === currentField?.name)?.id ?? 0,
        [currentField],
    )
    const projectId = useProjectId()
    const propValuesQuery = usePropValues(projectId, fieldId)

    const propertyValues: string[] = propValuesQuery.data ?? []

    const handleSave = () => {
        if (currentField && currentValue) {
            onSave({
                field: currentField,
                operator: currentOperator,
                value: currentValue,
            })
        }
    }

    return (
        <Card className="w-full max-w-md border-0 shadow-none">
            <CardHeader>
                <CardTitle>
                    {initialFilter ? 'Edit Filter' : 'Add Filter'}
                </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
                {/* Field Selector */}
                <div className="space-y-2">
                    <label className="text-sm font-medium">Field</label>
                    <Popover open={openField} onOpenChange={setOpenField}>
                        <PopoverTrigger asChild>
                            <Button
                                variant="outline"
                                role="combobox"
                                className="w-full justify-between"
                            >
                                {currentField ? (
                                    <>
                                        {currentField.name}
                                        <span className="ml-2 text-xs text-muted-foreground">
                                            {currentField.type}
                                        </span>
                                    </>
                                ) : (
                                    'Select field...'
                                )}
                                <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50"/>
                            </Button>
                        </PopoverTrigger>
                        {availableFields.length > 0 && (
                            <PopoverContent className="p-0">
                                <Command>
                                    <CommandInput placeholder="Search field..."/>
                                    <CommandEmpty>No field found.
                                        {Array.isArray(availableFields)}
                                    </CommandEmpty>
                                    <CommandList>
                                        {availableFields.map((field) => (
                                            <CommandItem
                                                key={field.name}
                                                onSelect={() => {
                                                    setCurrentField(field)
                                                    setOpenField(false)
                                                }}
                                            >
                                                <Check
                                                    className={`mr-2 h-4 w-4 ${
                                                        currentField?.name === field.name
                                                            ? 'opacity-100'
                                                            : 'opacity-0'
                                                    }`}
                                                />
                                                {field.name}
                                                <span className="ml-2 text-xs text-muted-foreground">
                                                    {field.type}
                                                </span>
                                            </CommandItem>
                                        ))}
                                    </CommandList>
                                </Command>
                            </PopoverContent>
                        )}
                    </Popover>
                </div>

                {/* Operator Selector */}
                <div className="space-y-2">
                    <label className="text-sm font-medium">Operator</label>
                    <Select
                        value={currentOperator}
                        onValueChange={(value) => setCurrentOperator(value as Operator)}
                    >
                        <SelectTrigger className="w-full">
                            <SelectValue placeholder="Select operator"/>
                        </SelectTrigger>
                        <SelectContent>
                            {operators.map((op) => (
                                <SelectItem key={op} value={op}>
                                    {op}
                                </SelectItem>
                            ))}
                        </SelectContent>
                    </Select>
                </div>

                {/* Value Selector */}
                <div className="space-y-2">
                    <label className="text-sm font-medium">Value</label>
                    <Popover open={openValue} onOpenChange={setOpenValue}>
                        <PopoverTrigger asChild>
                            <Button
                                variant="outline"
                                role="combobox"
                                className="w-full justify-between"
                            >
                                {currentValue || 'Enter value...'}
                                <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50"/>
                            </Button>
                        </PopoverTrigger>
                        <PopoverContent className="p-0">
                            <Command>
                                <CommandInput
                                    placeholder="Enter value"
                                    value={currentValue}
                                    onValueChange={setCurrentValue}
                                />
                                <CommandEmpty>No suggestion found.</CommandEmpty>
                                <CommandList className="max-h-[300px] overflow-y-auto">
                                    {currentField?.name === 'event_type'
                                        ? eventTypes.map((type) => (
                                            <CommandItem
                                                key={type}
                                                onSelect={() => {
                                                    setCurrentValue(type)
                                                    setOpenValue(false)
                                                }}
                                            >
                                                <Check
                                                    className={`mr-2 h-4 w-4 ${
                                                        currentValue === type
                                                            ? 'opacity-100'
                                                            : 'opacity-0'
                                                    }`}
                                                />
                                                {type}
                                            </CommandItem>
                                        ))
                                        : propertyValues?.map(
                                            (val) => (
                                                <CommandItem
                                                    key={val}
                                                    onSelect={() => {
                                                        setCurrentValue(val)
                                                        setOpenValue(false)
                                                    }}
                                                >
                                                    <Check
                                                        className={`mr-2 h-4 w-4 ${
                                                            currentValue === val
                                                                ? 'opacity-100'
                                                                : 'opacity-0'
                                                        }`}
                                                    />
                                                    {val}
                                                </CommandItem>
                                            )
                                        )}
                                </CommandList>
                            </Command>
                        </PopoverContent>
                    </Popover>
                </div>
            </CardContent>
            <CardFooter className="flex justify-end space-x-2">
                <Button variant="outline" onClick={onDiscard}>
                    {initialFilter ? 'Cancel' : 'Discard'}
                </Button>
                <Button onClick={handleSave}>
                    {initialFilter ? 'Update' : 'Create'}
                </Button>
            </CardFooter>
        </Card>
    )
}
